### ISSUE TITLE
Login with secondary/alternate User Accounts

### ISSUE THREAD

**Issue by logan-wrld** [Leto-gg/dashboard#4]
I created an account and AFTER logging out, I want to login to a different account but instead, the previous login token is used and the login is forwarded directly to whatever account was previously logged into.

Upon dashboard logout, get rid of the token that would allow logging back in without entering account credentials again or by having a seperate button for alternate account login

**Comment by m-yasir** [comment]
That's unintentional. The logout call to backend should remove the refresh token from the cookies and log you out from Cognito as well. I'll be looking into this issue.

**Comment by m-yasir** [comment]
This has been resolved.
